export { default as Sun } from "./buttons/sun.svg";
export { default as Moon } from "./buttons/Moon.svg";
export { default as Get } from "./buttons/Get.svg";
export { default as Stroke } from "./advantages/Stroke.svg";
export { default as StrokeT } from "./advantages/Stroke-2.svg";
export { default as StrokeSecond } from "./advantages/StrokeSecond.svg";
export { default as StrokeTwo } from "./advantages/StrokeTwo.svg";
export { default as StrokeThree } from "./advantages/StrokeThree.svg";
export { default as StrokeForth } from "./advantages/StrokeForth.svg";
export { default as StrokeSmallSecond } from "./advantages/StrokeSmallSecond.svg";
export { default as StrokeSmallThird } from "./advantages/StrokeSmallThird.svg";
export { default as StrokeSmallForth } from "./advantages/StrokeSmallForth.svg";
export { default as StrokeSmallFifth } from "./advantages/StrokeSmallFifth.svg";
export { default as StrokeSmallSixth } from "./advantages/StrokeSmallSixth.svg";
export { default as Persone } from "./advantages/Persone.svg";
export { default as Computer } from "./advantages/Computer.svg";
export { default as People } from "./advantages/People.svg";
export { default as Script } from "./advantages/Script.svg";
export { default as Time } from "./advantages/Time.svg";
export { default as Key } from "./advantages/key.svg";
export { default as ServicesBg } from "./services/ServicesBg.svg";
export { default as ServicesBgThree } from "./services/ServicesBgThree.svg";
export { default as ServicesBgFourth } from "./services/ServicesBgFourth.svg";
export { default as GetInTouch } from "./GetInTouch.svg";
export { default as Explore } from "./buttons/Explore.svg";
export { default as JiraIcon } from "./ourTechnilogy/jiraIcon.svg";
export { default as NotionIcon } from "./ourTechnilogy/NotionIcon.svg";
export { default as GitIcon } from "./ourTechnilogy/GitIcon.svg";
export { default as ConfluenceIcon } from "./ourTechnilogy/ConfluenceIcon.svg";
export { default as Planning } from "./work-process/Planning.svg";
export { default as Design } from "./work-process/Design.svg";
export { default as Testing } from "./work-process/Testing.svg";
export { default as Support } from "./work-process/Support.svg";
export { default as Number } from "./contactUs/Number.svg";
export { default as Dot } from "./contactUs/Dot.svg";
export { default as Blur } from "./contactUs/Blur.svg";
export { default as BlurSmall } from "./contactUs/BlurSmall.svg";
export { default as Vk } from "./contactUs/Vk.svg";
export { default as Tg } from "./contactUs/Tg.svg";
export { default as Facebook } from "./contactUs/Facebook.svg";
export { default as Inst } from "./contactUs/Inst.svg";
export { default as Linkedin } from "./contactUs/Linkedin.svg";
export { default as World } from "./contactUs/World.svg";
export { default as Be } from "./contactUs/Be.svg";
export { default as ContactStroke } from "./contactUs/ContactStroke.svg";
export { default as ContactStrokeSecond } from "./contactUs/ContactStrokeSecond.svg";
export { default as ContactStrokeThree } from "./contactUs/ContactStrokeThree.svg";
export { default as ContactStrokeFourth } from "./contactUs/ContactStrokeFourth.svg";
export { default as ContactStrokeSmall } from "./contactUs/ContactStrokeSmall.svg";
export { default as SendStrokeSecond } from "./contactUs/SendStrokeSecond.svg";
export { default as SendStroke } from "./contactUs/SendStroke.svg";

// import StrokeThree from "./StrokeThree.svg";
// import StrokeForth from "./StrokeForth.svg";
// import OurWorks from "./OurWorks.svg";
// import OurWorksSecond from "./OurWorksSecond.svg";
// import OurWorksThree from "./OurWorksThree.svg";
// import OurWorksFourth from "./OurWorksFourth.svg";
// import StrokeOurWorks from "./StrokeOurWorks.svg";
// import StrokeOurWorksSecond from "./StrokeOurWorksSecond.svg";

// import Arrow from "./contactUs/Arrow.svg";
// import CheckIcon from "./contactUs/CheckIcon.svg";
