export { default as Sun } from "./buttons/sun.svg";
export { default as Moon } from "./buttons/Moon.svg";
export { default as Get } from "./buttons/Get.svg";
export { default as Stroke } from "./advantages/Stroke.svg";
export { default as StrokeT } from "./advantages/Stroke-2.svg";
export { default as StrokeSecond } from "./advantages/StrokeSecond.svg";
export { default as StrokeTwo } from "./advantages/StrokeTwo.svg";
export { default as StrokeThree } from "./advantages/StrokeThree.svg";
export { default as StrokeForth } from "./advantages/StrokeForth.svg";
export { default as StrokeSmallSecond } from "./advantages/StrokeSmallSecond.svg";
export { default as StrokeSmallThird } from "./advantages/StrokeSmallThird.svg";
export { default as StrokeSmallForth } from "./advantages/StrokeSmallForth.svg";
export { default as StrokeSmallFifth } from "./advantages/StrokeSmallFifth.svg";
export { default as StrokeSmallSixth } from "./advantages/StrokeSmallSixth.svg";
export { default as Persone } from "./advantages/Persone.svg";
export { default as Computer } from "./advantages/Computer.svg";
export { default as People } from "./advantages/People.svg";
export { default as Script } from "./advantages/Script.svg";
export { default as Time } from "./advantages/Time.svg";
export { default as Key } from "./advantages/key.svg";
export { default as ServicesBg } from "./services/ServicesBg.svg";
export { default as ServicesBgThree } from "./services/ServicesBgThree.svg";
export { default as ServicesBgFourth } from "./services/ServicesbgFourth.svg";
export { default as GetInTouch } from "./GetInTouch.svg";
export { default as Explore } from "./buttons/Explore.svg";
export { default as JiraIcon } from "./ourTechnilogy/jiraIcon.svg";
export { default as NotionIcon } from "./ourTechnilogy/NotionIcon.svg";
export { default as GitIcon } from "./ourTechnilogy/GitIcon.svg";
export { default as ConfluenceIcon } from "./ourTechnilogy/ConfluenceIcon.svg";
export { default as Planning } from "./work-process/Planning.svg";
export { default as Design } from "./work-process/Design.svg";
export { default as Testing } from "./work-process/Testing.svg";
export { default as Support } from "./work-process/Support.svg";
export { default as Number } from "./contactUs/Number.svg";
export { default as Dot } from "./contactUs/Dot.svg";
export { default as Blur } from "./contactUs/Blur.svg";
export { default as BlurAverage } from "./contactUs/BlurAverage.svg";
export { default as BlurSmall } from "./contactUs/BlurSmall.svg";
export { default as BlurSmallSmall } from "./contactUs/BlurSmallSmall.svg";
export { default as Vk } from "./contactUs/Vk.svg";
export { default as Tg } from "./contactUs/Tg.svg";
export { default as Facebook } from "./contactUs/Facebook.svg";
export { default as Inst } from "./contactUs/Inst.svg";
export { default as Linkedin } from "./contactUs/Linkedin.svg";
export { default as World } from "./contactUs/World.svg";
export { default as Be } from "./contactUs/Be.svg";
export { default as ContactStroke } from "./contactUs/ContactStroke.svg";
export { default as ContactStrokeExtraSmall } from "./contactUs/ContactStrokeExtraSmall.svg";
export { default as ContactStrokeAverage } from "./contactUs/ContactStrokeAverage.svg";
export { default as ContactStrokeMobile } from "./contactUs/ContactStrokeMobile.svg";
export { default as ContactStrokeSecond } from "./contactUs/ContactStrokeSecond.svg";
export { default as ContactStrokeThree } from "./contactUs/ContactStrokeThree.svg";
export { default as ContactStrokeFourth } from "./contactUs/ContactStrokeFourth.svg";
export { default as ContactStrokeFourthSmall } from "./contactUs/ContactStrokeFourthSmall.svg";
export { default as ContactStrokeFourthExtraSmall } from "./contactUs/ContactStrokeFourthExtraSmall.svg";
export { default as ContactStrokeSmall } from "./contactUs/ContactStrokeSmall.svg";
export { default as SendStrokeSecond } from "./contactUs/SendStrokeSecond.svg";
export { default as SendStroke } from "./contactUs/SendStroke.svg";

export { default as Adobe } from "./ourTechnilogy/Adobe.svg";
export { default as Android } from "./ourTechnilogy/Android.svg";
export { default as Angular } from "./ourTechnilogy/Angular.svg";
export { default as Discord } from "./ourTechnilogy/Discord.svg";
export { default as Docker } from "./ourTechnilogy/Docker.svg";
export { default as Figma } from "./ourTechnilogy/Figma.svg";
export { default as Flutter } from "./ourTechnilogy/Flutter.svg";
export { default as Github } from "./ourTechnilogy/Github.svg";
export { default as Golang } from "./ourTechnilogy/Golang.svg";
export { default as Java } from "./ourTechnilogy/Java.svg";
export { default as Javascript } from "./ourTechnilogy/Javascript.svg";
export { default as Laravel } from "./ourTechnilogy/Laravel.svg";
export { default as Mongodb } from "./ourTechnilogy/Mongodb.svg";
export { default as MySql } from "./ourTechnilogy/Mysql.svg";
export { default as NextJs } from "./ourTechnilogy/Next-js.svg";
export { default as NodeJs } from "./ourTechnilogy/Node-js.svg";
export { default as Php } from "./ourTechnilogy/Php.svg";
export { default as PostgreSQL } from "./ourTechnilogy/PostgreSQL.svg";
export { default as Pyton } from "./ourTechnilogy/Pyton.svg";
export { default as ReactIcon } from "./ourTechnilogy/React.svg";
export { default as Sql } from "./ourTechnilogy/Sql.svg";
export { default as Symphony } from "./ourTechnilogy/Symphony.svg";
export { default as TypeScript } from "./ourTechnilogy/Type-script.svg";
export { default as Vue } from "./ourTechnilogy/Vue.svg";

// import StrokeThree from "./StrokeThree.svg";
// import StrokeForth from "./StrokeForth.svg";
// import OurWorks from "./OurWorks.svg";
// import OurWorksSecond from "./OurWorksSecond.svg";
// import OurWorksThree from "./OurWorksThree.svg";
// import OurWorksFourth from "./OurWorksFourth.svg";
// import StrokeOurWorks from "./StrokeOurWorks.svg";
// import StrokeOurWorksSecond from "./StrokeOurWorksSecond.svg";

// import Arrow from "./contactUs/Arrow.svg";
// import CheckIcon from "./contactUs/CheckIcon.svg";
